#!/bin/bash

#postrm script for sandbox

#set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#### Variables
PVECTL_BIN=/usr/bin/pvectl
VMID=10

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
fi

case "$1" in
        purge|remove|disappear)
                $PVECTL_BIN stop $VMID 
		$PVECTL_BIN destroy $VMID
		mv /etc/resolv.conf /etc/resolv.conf.sandbox
		mv /etc/interfaces /etc/interfaces.sandbox
		mv /etc/resolv.conf.old /etc/resolv.conf
		mv /etc/interfaces.old /etc/interfaces
                ;;
        upgrade|failed-upgrade|abort-install|abort-upgrade)
                ;;
        *)
                echo "postrm called with unknown argument \`$1'" >&2
                exit 1
                ;;
esac

exit 0

